Create factory web driver initializer
GFLCourses7/worker pull request #27
Opened 2024-02-20 18:27 UTC by Modgens

2024-02-21 13:04 UTC, MrMarkutan requested changes
I think we need a factory here (according to the card #21 on trello board)

2024-02-21 13:21 UTC, MrMarkutan commented on src/main/java/executor/service/utils/WebDriverInitializer.java
> +    public WebDriver init(WebDriverConfig webDriverConfig, ProxyConfigHolder proxyConfigHolder) {
where do we get WebDriverConfig? we need to parse it from properties. And ProxyConfigHolder comes from ProxySourcesClient.getProxy(). Correct me, if I am mistaken.

2024-02-21 13:27 UTC, MrMarkutan commented on target/classes/executorService.properties
added in this pr d906975c696719900f7361878d2d25b0dceea1b2

2024-02-21 13:30 UTC, MrMarkutan commented on src/main/java/executor/service/utils/WebDriverInitializer.java
> +    public WebDriver init(WebDriverConfig webDriverConfig, ProxyConfigHolder proxyConfigHolder) {
Or should DI factory parse configs?

2024-02-25 15:34 UTC, DenysKravets requested changes

2024-02-25 15:34 UTC, DenysKravets commented on src/main/java/executor/service/utils/WebDriverConfigExecutor.java
> +}
Class contents are empty, implementation is probably still on your local machine.

2024-02-27 11:06 UTC, merged